services:
  - type: web
    name: simco-notification-backend
    runtime: python
    rootDir: services/notification_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: kamdem.guy@institutsaintjean.org
      - key: MAIL_PASSWORD
        value: krcmwwfwnomgwmgi
      - key: MAIL_STARTTLS
        value: true
      - key: MAIL_AUTH
        value: true
      - key: MAIL_FROM_NAME
        value: SIMCO Notifications
